# Site settings
title: "Resume"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Tsianos Antonios"
resume_title:                   "Administation Liason"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "atiano81@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "6979999999"
resume_contact_address:         "Salonica land of truth"

resume_header_contact_info:     ""
display_header_contact_info:    "false"

resume_header_intro: "<p></p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
#resume_section_projects:        false
resume_section_skills:          true
#resume_section_recognition:     false
resume_section_links:           true
#resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/atsiano81"
  #resume_twitter_url:           ""
  #resume_dribbble_url:          ""
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          ""
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           ""
  #resume_medium_url:            ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
